### ISSUE TITLE
User configurable keys

### ISSUE THREAD

**Issue by nikhilkumarsingh** [coding-blocks/clix#1]
Currently clix GUI opens on **Ctrl** + **space** keys.
Add a command line argument which permits user to set keys explicitly.

**Comment by dibyadas** [comment]
@nikhilkumarsingh I would like to work on this issue. Can you assign this to me?

**Comment by nikhilkumarsingh** [comment]
@dibyadas You can start working on it and make a pull request.
You will need to use argparse module. Please see the main function of this [script](https://github.com/coding-blocks/content-downloader/blob/master/ctdl/ctdl.py) for reference .

**Comment by dibyadas** [comment]
@nikhilkumarsingh Thanks! 
I followed the steps mentioned in the README to setup but after installing the requirements, I am getting `ImportError` for Xlib module. I guess that is not mentioned in the requirements.txt file.

**Comment by nikhilkumarsingh** [comment]
Tkinter comes pre-installed with Python.
I have added instructions to download Xlib module in latest commit.
Thanks.

**Comment by nikhilkumarsingh** [comment]
@championswimmer  The task has been completed.
